//ALL action types will be exported here.


//Login actionTypes
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

//register actionTypes
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

//create family actionTypes
export const REQUEST_CREATE_FAMILY = 'REQUEST_CREATE_FAMILY';
export const CREATE_FAMILY_SUCCESS = 'CREATE_FAMILY_SUCCESS';
export const CREATE_FAMILY_FAILED = 'CREATE_FAMILY_FAILED';

export const REQUEST_ADD_MEMBER = 'REQUEST_ADD_MEMBER';
export const ADD_MEMBER_SUCCESS = 'ADD_MEMBER_SUCCESS';
export const ADD_MEMBER_FAILED = 'ADD_MEMBER_FAILED';

//photo album actionTypes
export const REQUEST_GET_IMAGES = 'REQUEST_GET_IMAGES';
export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';
export const GET_IMAGES_FAILURE = 'GET_IMAGES_FAILURE';

export const REQUEST_ADD_URL = 'REQUEST_ADD_URL';
export const ADD_URL_SUCCESS = 'ADD_URL_SUCCESS';
export const ADD_URL_FAILED = 'ADD_URL_FAILED';


export const REQUEST_UPLOAD_IMAGE = 'REQUEST_UPLOAD_IMAGE';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE';
//Filler action types:
export const ACTION_CALL = 'ACTION_CALL';
export const CALL_RECIEVED = 'CALL_RECIEVED';
export const CALL_FAILED = 'CALL_FAILED';

export const LOG_OUT = 'LOG_OUT';

export const REQUEST_LOAD_CALENDAR = 'REQUEST_LOAD_CALENDAR';
export const LOAD_CALENDAR_SUCCESS = 'LOAD_CALENDAR_SUCCESS';
export const LOAD_CALENDAR_FAILED = 'LOAD_CALENDAR_FAILED';

export const REQUEST_ADD_EVENT = 'REQUEST_ADD_EVENT';
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS';
export const ADD_EVENT_FAILURE = 'ADD_EVENT_FAILURE';
